### ISSUE TITLE
grub.cfg line 132 ?

### ISSUE THREAD

**Issue by steve6375** [schierlm/usb-modboot#1]
https://github.com/schierlm/usb-modboot/blob/master/grub.cfg
menuentry $"GRUB configuration" {
	set incmode=cfg
	configfile (core)/boot/grub/grub.cfg
	if [ "$incmode" = "cfgafter" ]; then
		set incmode=main
		clear_menu
		**source (core/boot/grub/grub.cfg**
	fi
	set incmode=main
}

I haven't tried this project yet, but this line caught my eye - is it correct?

**Comment by schierlm** [comment]
No, that is not correct. But apparently that path (returning to the main menu after changing the language) was not tested well :(

Will push a fix in a minute.
